### PR TITLE
[BUG] Remove amount and schools header

### PR DESCRIPTION
**Pull request by MikolJiron**

### CODE REVIEW

**Review by Lorraine-Lyu — APPROVED** [review]
I'll just approve this PR. Hopefully we can change our table into a list later.

**Review by tinagrasso — APPROVED** [review]
Are you coordinating with Lorraine on her grid changes?

**Review by hzimz — APPROVED** [review]

**Review by CarlosM10011 — CHANGES_REQUESTED** [review]
I'm getting these linter messages:

```
src/main/webapp/js/datahandlers/scholarshiplistdatahandler.js:24: WARNING - [JSC_UNUSED_LOCAL_ASSIGNMENT] Value assigned to local variable AMOUNT_PER_YEAR is never read
  24| const AMOUNT_PER_YEAR = 'amountPerYear';
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/main/webapp/js/datahandlers/scholarshiplistdatahandler.js:25: WARNING - [JSC_UNUSED_LOCAL_ASSIGNMENT] Value assigned to local variable ELLIPSIS is never read
  25| const ELLIPSIS = '...';
            ^^^^^^^^^^^^^^^^

src/main/webapp/js/datahandlers/scholarshiplistdatahandler.js:26: WARNING - [JSC_UNUSED_LOCAL_ASSIGNMENT] Value assigned to local variable END_OF_STRING is never read
  26| const END_OF_STRING = 23;
            ^^^^^^^^^^^^^^^^^^

src/main/webapp/js/datahandlers/scholarshiplistdatahandler.js:29: WARNING - [JSC_UNUSED_LOCAL_ASSIGNMENT] Value assigned to local variable UNKNOWN is never read
  29| const UNKNOWN = 'unknown';
            ^^^^^^^^^^^^^^^^^^^
```

**Comment by CarlosM10011** [comment]
Also this branch appears to be behind devel. Please rebase and run the compiler to see if it builds without errors / warnings.

**Pull request closed without merging**
