### PR TITLE
Add initial project structure

### PR DESCRIPTION
**Pull request by CarlosM10011**
This pull request adds the initial structure for the project.

### CODE REVIEW

**Comment by CarlosM10011** [comment]
@googlebot I signed it!

**Review by MikolJiron — COMMENTED** [review]
LGTM, except we might need to change the index.html to a index.soy file.

**Comment by CarlosM10011** [comment]
Yeah, I'm working on adding closure compiler to the build process atm.

**Comment by CarlosM10011** [comment]
This should complete the project structure configuration.

**Review by Lorraine-Lyu — APPROVED** [review]

**Review by MikolJiron — APPROVED** [review]
LGTM

**Review by hzimz — APPROVED** [review]

**Review by tinagrasso — APPROVED** [review]

**Pull request merged**
